[general]
connection = "Server=192.168.0.41,1433; Database=NotaFiscalDb; User Id=iuri; Password=1495;encrypt=False"
output = "DbAutoGen.fs"
namespace = "NotaFiscal.Data.DbAutoGen"
cli_mutable = true
[sqlhydra_query_integration]
provider_db_type_attributes = true
table_declarations = true
[readers]
reader_type = "Microsoft.Data.SqlClient.SqlDataReader"
[filters]
include = ["*.*"]
exclude = ["dbo/NotaFiscalServico.DataCriacao", "dbo/NotaFiscalServico.DataAlteracao"]
